### ISSUE TITLE
Error using npx

### ISSUE THREAD

**Issue by aarongarciah** [Kikobeats/automate-release#26]
Executing the `npx automate-release` throws the following error:

![image](https://user-images.githubusercontent.com/7225802/86402417-1327e580-bcac-11ea-841c-601aaa045547.png)

**Comment by Kikobeats** [comment]
Hey @aarongarciah, sorry about that!

It should be fixed at https://github.com/Kikobeats/automate-release/commit/121f74cf7d9dbfd7989ced226f5bffaab5085f28

Can you try again? 🙂

**Comment by aarongarciah** [comment]
Works wonders! Thanks 😄
